### ISSUE TITLE
It does not work inside docker Docker image

### ISSUE THREAD

**Issue by mitar** [christian-korneck/docker-pushrm#1]
I am trying to run it inside Docker-in-Docker:

```baseh
$ docker run --rm -t -i docker:19
$ wget https://github.com/christian-korneck/docker-pushrm/releases/download/v1.0.0/docker-pushrm_linux_amd64
$ mkdir -p $HOME/.docker/cli-plugins
$ mv docker-pushrm_linux_amd64 $HOME/.docker/cli-plugins/docker-pushrm
$ chmod +x $HOME/.docker/cli-plugins/docker-pushrm
$ docker --help
...
Invalid Plugins:
  pushrm      failed to fetch metadata: exit status 127
...
```

**Comment by christian-korneck** [comment]
hi @mitar, thanks for the info!

I just briefly tested and it looks like there's an issue with running `docker-pushrm` on alpine (which the `docker:19` image is based on) and Docker "from scratch" images. It silently dies with exit code 127.

I'll investigate and push a patch as soon as I know what the problem is.

In the meantime, is there any chance that you could run it on a different Docker base image? (It worked fine for me on ubuntu/debian/centos/fedora etc). You don't actually need the Docker CLI tool to run it, you can just execute `./docker-pushrm` directly.

**Comment by christian-korneck** [comment]
hi @mitar,

this has been fixed in [v1.0.1](https://github.com/christian-korneck/docker-pushrm/releases/tag/v1.0.1).

Here's a basic example with the `docker:19` container image that works for me (for simplicity I'm copying the README file and the Docker config file (with the credentials) in the Dockerfile, but you could of course also mount them as volume). I took the liberty to add a slightly more complex line for downloading the plugin from github releases that I'm using in my own CI jobs. It uses a (hopefully) save/stable api call to find the download url of the latest release.

```
$ ls
Dockerfile	README.md	config.json
```

contents of `Dockerfile`:
```
FROM docker:19
USER root
RUN mkdir -p /root/.docker/
COPY ./config.json /root/.docker/config.json
COPY ./README.md /README.md
RUN apk add curl jq
RUN export FILENAME=docker-pushrm_linux_amd64 && export DESTDIR=$HOME/.docker/cli-plugins && mkdir -p "$DESTDIR" && DOWNLOAD_URL=$(curl --silent --fail --show-error https://api.github.com/repos/christian-korneck/docker-pushrm/releases/latest | jq -r ".assets | map(select(.name == \"$FILENAME\"))[0].browser_download_url") && curl --silent --fail --show-error -L $DOWNLOAD_URL -o "$DESTDIR/docker-pushrm" && chmod +rx "$DESTDIR/docker-pushrm"
```

contents of `config.json`:

```
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "bXl1c2VyOm15cGFzc3dvcmQ="
		},
		"demo.goharbor.io": {
			"auth": "bXl1c2VyOm15cGFzc3dvcmQ="
		},
		"quay.io": {
			"auth": "bXl1c2VyOm15cGFzc3dvcmQ="
		}
	},
	"plugins": {
		"docker-pushrm": {
			"apikey_quay.io": "my-quay-api-key-in-clear-text"
		}
	}
}
```

(I've created this file on my workstation by running `docker login` and then copying the relevant parts from `$HOME/.docker/config.json`. If you want to create it manually, the auth values are base64 of `user:passwd`. The Quay API key is clear text. You could of course also do a `docker login` inside of the container, but please note that this requires a connection to a running docker engine in a `dind` (docker in docker) container as described here: https://hub.docker.com/_/docker . (I'm passing on this here for simplicity, but it works, too.))

then:
```
$ docker build -t mydocker:19 . --no-cache
$ docker run --rm -t mydocker:19 docker pushrm my-user/my-repo --debug
...
DEBU content validation successfull, readme successfully pushed to repo server
```

Hope this helps - let me know if you have any questions or run into further problems.

Best,
Chris

**Comment by mitar** [comment]
> It uses a (hopefully) save/stable api call to find the download url of the latest release.

I do not want the latest release in my CI jobs, but a fixed one. :-) CI jobs broke too many times because of a third party upgrade.

Thanks for fixing this. I will try it later today.

**Comment by christian-korneck** [comment]
> I do not want the latest release in my CI jobs, but a fixed one. :-)

sure - your command works fine as well :)

**Comment by christian-korneck** [comment]
@mitar : 

> You could of course also do a docker login inside of the container, but please note that this requires a connection to a running docker engine in a dind (docker in docker) container

Regarding running docker-pushrm in a container: To avoid that you need a running Docker engine (with all the overhead and security issues of a Docker in Docker setup) just to be able to run `docker login` it's now (since v1.2.0) possible to pass credentials to docker-pushrm via env vars. So you don't need anything else in your container besides the `docker-pushrm` executable. I've also added a `--file <path>` option to access a README file in another path (to access a README in a container volume).

Example:
```
DOCKER_USER=my-user DOCKER_PASS=my-password ./docker-pushrm --file /myvol/README.md my-user/my-repo
```

**Comment by mitar** [comment]
Awesome! This tool is getting better and better. :-)

**Comment by christian-korneck** [comment]
and there's now also a Dockerfile / container image:
https://github.com/christian-korneck/docker-pushrm#running-docker-pushrm-as-a-container
