### ISSUE TITLE
Conflict with Dockerhub personal access tokens and 2FA auth

### ISSUE THREAD

**Issue by modem7** [christian-korneck/docker-pushrm#18]
Heya,

Just an FYI, there's an update on this particular issue. 

https://github.com/docker/hub-feedback/issues/2127#issuecomment-1082247689

Hope that helps!

**Comment by christian-korneck** [comment]
@modem7 thanks!! I’ll have a look.

**Comment by christian-korneck** [comment]
I tried but [it doesn't seem to work](https://github.com/docker/hub-feedback/issues/2127#issuecomment-1152831106) for me.

**Comment by modem7** [comment]
Thankfully thanks to your additional input, they've re-opened the issue, so hopefully we'll get somewhere with it sometime soon!

Cheers for looking!

**Comment by christian-korneck** [comment]
since today's [Docker Hub API change](https://github.com/docker/hub-feedback/issues/2127#issuecomment-1183192693) PATs seem to be working with `docker-pushrm`. I've removed all warnings about this limitation from the README and the code in [v1.9.0](https://github.com/christian-korneck/docker-pushrm/releases/tag/v1.9.0).

@modem7 thanks again for your help.
